### ISSUE TITLE
ERROR For preprocessing

### ISSUE THREAD

**Issue by yuguochencuc** [onejiin/CycleGAN-VC2#1]
excuse me.could you please tell me why there is an error when i preprocess vcc2016 data.
when i run the code, "python train.py --train_A_dir ./data/vcc2016_training/SF1 --train_B_dir ./data/vcc2016_training/TM1 --model_dir ./model/sf1_tm1 --model_name sf1_tm1.ckpt --random_seed 0 --gen_model CycleGAN-VC2 --validation_A_dir ./data/evaluation_all/SF1 --validation_B_dir ./data/evaluation_all/TM1 --output_dir ./validation_output --tensorboard_log_dir ./log --MCEPs_dim 24".i don't know  why there is a traceback.Traceback (most recent call last):
  File "train.py", line 265, in <module>
    hdf5_path=[hdf5A_path, hdf5B_path], lambda_list=[lambda_cycle, lambda_identity])
  File "train.py", line 57, in train
    log_f0s_mean_A, log_f0s_std_A = logf0_statistics(f0s_A)
  File "/home/yuguochen/CycleGAN-VC2/preprocess.py", line 162, in logf0_statistics
    log_f0s_concatenated = np.ma.log(np.concatenate(f0s))
ValueError: need at least one array to concatenate
i want know what is the "hdf5A_path"? do i need  put the data into this path?

**Comment by yuguochencuc** [comment]
thanks a lot for answering  my question.

**Comment by onejiin** [comment]
Hi,
This is an error to HDF5 directory existence.
If you want to train a short utterance like vcc2016, you do not need to write data db as HDF5.
Because I modified code, you can run hdf5A_path=None (Default is None)
Please update code by using git clone.
Best,
