### ISSUE TITLE
Memory leaking bug

### ISSUE THREAD

**Issue by jxzhanggg** [onejiin/CycleGAN-VC2#4]
Hi, Thanks for your work. 
I found the train process got slower and slower during running. After inspection, I suspect 
there's memory leaking problem in your code. In "train.py", model.summary() is called, which will 
add the computing graph new node each training step. This will make the computational graph larger and larger and leading to slower training. Actually, this function is already called and added to the graph at the model.py _init_() the last line "... = self.summary()".
If you check the leimao's original code, you'll find it doesn't have this line.
Removing this model.summary() at train.py will fix the memory leaking bug.

**Comment by onejiin** [comment]
Thanks for your comment
I fixed and commit
Best,
